"""
============================================================
04_qc_dashboard.py
Purpose: Generate visual QC dashboard for study team review
Study:   XYZ-2026
Author:  Careen Chowrappa
============================================================
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np

disc = pd.read_csv('outputs/discrepancy_database.csv')
disc['SITE'] = disc['USUBJID'].apply(
    lambda x: f"Site {x.split('-')[2]}" if len(str(x).split('-')) >= 3 else 'Unknown')

fig = plt.figure(figsize=(18, 12), facecolor='white')
fig.suptitle('Study XYZ-2026 — Clinical Data QC Dashboard\n'
             'Proactive Data Integrity Framework | Pre-Lock Assessment',
             fontsize=16, fontweight='bold', y=0.98, color='#2c3e50')

gs = gridspec.GridSpec(2, 3, hspace=0.35, wspace=0.35,
                       top=0.90, bottom=0.08, left=0.06, right=0.96)

colors = {'DM': '#3498db', 'AE': '#e74c3c', 'VS': '#2ecc71',
          'LB': '#f39c12', 'CM': '#9b59b6'}

# --- Panel 1: Queries by Domain ---
ax1 = fig.add_subplot(gs[0, 0])
domain_counts = disc['DOMAIN'].value_counts()
bars = ax1.bar(domain_counts.index, domain_counts.values,
               color=[colors.get(d, '#95a5a6') for d in domain_counts.index],
               edgecolor='white', linewidth=1.5)
for bar, val in zip(bars, domain_counts.values):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
             str(val), ha='center', fontweight='bold', fontsize=11)
ax1.set_title('Queries by Domain', fontweight='bold', fontsize=12, pad=10)
ax1.set_ylabel('Count')
ax1.spines['top'].set_visible(False)
ax1.spines['right'].set_visible(False)

# --- Panel 2: Query Status ---
ax2 = fig.add_subplot(gs[0, 1])
status_counts = disc['STATUS'].value_counts()
status_colors = {'CLOSED': '#27ae60', 'OPEN': '#e74c3c', 'ANSWERED': '#f39c12'}
wedges, texts, autotexts = ax2.pie(
    status_counts.values,
    labels=status_counts.index,
    autopct='%1.1f%%',
    colors=[status_colors.get(s, '#95a5a6') for s in status_counts.index],
    startangle=90,
    textprops={'fontsize': 10}
)
for autotext in autotexts:
    autotext.set_fontweight('bold')
ax2.set_title('Query Status Distribution', fontweight='bold', fontsize=12, pad=10)

# --- Panel 3: Severity ---
ax3 = fig.add_subplot(gs[0, 2])
sev = disc.groupby(['SEVERITY', 'STATUS']).size().unstack(fill_value=0)
sev.plot(kind='bar', stacked=True, ax=ax3,
         color=['#f39c12', '#e74c3c', '#27ae60'], edgecolor='white')
ax3.set_title('Severity × Status', fontweight='bold', fontsize=12, pad=10)
ax3.set_ylabel('Count')
ax3.legend(title='Status', frameon=False)
ax3.tick_params(axis='x', rotation=0)
ax3.spines['top'].set_visible(False)
ax3.spines['right'].set_visible(False)

# --- Panel 4: Top Failing Edit Checks ---
ax4 = fig.add_subplot(gs[1, 0:2])
top_checks = disc['CHECK_ID'].value_counts().head(10)
bars4 = ax4.barh(range(len(top_checks)), top_checks.values, color='#3498db',
                  edgecolor='white', linewidth=1)
ax4.set_yticks(range(len(top_checks)))
ax4.set_yticklabels(top_checks.index, fontsize=9)
for bar, val in zip(bars4, top_checks.values):
    ax4.text(bar.get_width() + 0.2, bar.get_y() + bar.get_height()/2,
             str(val), va='center', fontweight='bold')
ax4.set_title('Top 10 Failing Edit Checks', fontweight='bold', fontsize=12, pad=10)
ax4.set_xlabel('Number of Queries')
ax4.invert_yaxis()
ax4.spines['top'].set_visible(False)
ax4.spines['right'].set_visible(False)

# --- Panel 5: Queries by Site ---
ax5 = fig.add_subplot(gs[1, 2])
site_data = disc.groupby('SITE')['STATUS'].value_counts().unstack(fill_value=0)
site_data.plot(kind='bar', stacked=True, ax=ax5,
               color=['#f39c12', '#e74c3c', '#27ae60'], edgecolor='white')
ax5.set_title('Queries by Site', fontweight='bold', fontsize=12, pad=10)
ax5.set_ylabel('Count')
ax5.legend(title='Status', frameon=False, fontsize=8)
ax5.tick_params(axis='x', rotation=45)
ax5.spines['top'].set_visible(False)
ax5.spines['right'].set_visible(False)

# Footer
fig.text(0.5, 0.02,
         'Generated by Automated QC Engine | Careen Chowrappa | March 2026 | '
         'Framework: Python + SAS | Standards: CDISC SDTM, ICH E6(R3), 21 CFR Part 11',
         ha='center', fontsize=8, color='#7f8c8d', style='italic')

plt.savefig('outputs/qc_dashboard.png', dpi=200, bbox_inches='tight',
            facecolor='white')
plt.close()
print("✅ QC Dashboard saved: outputs/qc_dashboard.png")